- readme.md
> Test commit for project board

- PULL_REQUEST_TEMPLATE.md
- readme.md
*This PR closes #x*
*Provide a brief summary of the change(s) included in this pull request*
*Share the reason(s) for this pull request*
> Add live site to README

- module1/lessons/index.md
- module1/lessons/intro_to_testing.md
*This PR closes...issue #18 *
- Added note that these concepts apply to programming in general, not just Ruby.
- Added the same testing example in JS at the end.
- Please look at the note added to the end.  I wanted to keep it separate from the lesson content so I used the standard box styling at the end.  Does it look ok set up that way?
> Intro to testing lesson

- module1/lessons/intro_to_testing.md
Already closed.
Just adding a link to the exercise repo to the lesson itself.  Merging without review.
> Fix spelling and link to se exercises repo

- module1/lessons/beginner_enumerables.md
- module1/lessons/index.md
- module1/lessons/iteration.md
This PR closes #26 
- Adds javascript to the Beginner Enumerables Lesson
- Adds Iteration lesson (to be done as hw before lesson) 
Please double check my javascript!
> Beginning enumerables closes #26

- module1/lessons/index.md
- module1/lessons/intro_to_how_the_web_works.md
*This PR closes [#41](https://github.com/turingschool/curriculum-site/issues/41)*
This PR enhances the lesson by adding detailed definitions for key vocabulary terms. The goal is to make the content more accessible and easier to understand for students.
No major changes were made to the structure or content of the lesson, just additional context to clarify important terms.
> Added detailed definitions for key vocabulary terms to improve clarity

- module1/lessons/index.md
#33 
* Because this is a workshop, I did not add any JavaScript.  It didn't seem helpful at this point to add exercises in a different language.  I think in the future we could add some optional javascript exercises, but that's a larger discussion.
N/A
> Uncomment Link

- module1/lessons/index.md
- module1/lessons/intermediate_enumerables.md
#31 Intermediate Enumerables
- Adds link to the new SE Mod 1 Exercises Repo
I did not include JS since at this point, I think the JS examples would get more complex and might confuse/overwhelm students. This lesson is pretty meaty.
> Update Intermediate Enumerables lesson.

- module1/lessons/git_collaboration.md
- module1/lessons/git_sample_flow.md
- module1/lessons/index.md
No - this is a rogue PR aligning small things I found while setting up the SE1 calendar
When updating the links in the SE1 calendar I noticed the Git Workflow lesson still had links to the fe site.  Then I found there was some mismatched files/links/naming so I corrected it.
None, merging immediately
> Align git resources

- module1/lessons/learning_to_pair.md
Test commit to look into merge conflict
No issues found - merging one change which points the DTR link to the new copy created in the SE gdrive
> Test discrepancy

- module1/lessons/index.md
- module1/lessons/test_driven_development.md
#23 
Adds more specific examples of testing command vs query methods.
Removes "turn and talk" references.
I didn't include and JS in this one. Open to adding some if you think it's helpful.
> Update TDD lesson

- module1/lessons/debugging_prework.md
- module1/lessons/index.md
*This PR closes. issue #21 *
- Creates a small lesson plan for this exercise rather than having the instructions and links found in various google docs and the calendar event.
- Added the CFU questions to the Self Assessment quiz so we can get rid of the CFU google doc
- Links this exercise in the lessons page
Just a quick set of eyes.  No content change, just combining resources to one lesson plan
> Async debugging

- module0/lessons/arrays.md
- module0/lessons/asking_qs.md
- module0/lessons/calendaring.md
- module0/lessons/conditionals.md
- module0/lessons/data_types.md
- module0/lessons/dtr.md
- module0/lessons/git.md
- module0/lessons/github.md
- module0/lessons/hashes.md
- module0/lessons/iteration.md
- module0/lessons/methods.md
- module0/lessons/oop.md
- module0/lessons/pairing.md
- module0/lessons/problem-solving.md
- module0/lessons/testing.md
*This PR closes...*
Update styling classes to no longer use mod0.scss file
> Update styling classes to no longer use mod0.scss file

- module0/prework/markdown.md
- module0/prework/vs-code.md
This PR closes... nothing yet
Removed mod0.scss in prework for mod 0
mod0/prework/syllabus.md has a css "try-it" that is being used site wide. I left it in bc after commenting it out in the mod0.scss it remained unchanged - I want to check that leaving it in was correct
> Mod0 prework formatting

- module1/lessons/class_methods.md
- module1/lessons/index.md
*This PR closes...* #34 
Just general feedback is ok. I go back and forth with knowing how many "Note" boxes is too much before the page seems bloated with them, so if you have any feedback on the number I have here or the content within them, that would be great.
> updates class methods with js examples

- module2/lessons/beginner_rails_workshop.md
- module2/lessons/index.md
*This PR closes 92 task manager worktime  self teach*
- Add beginner rails beginner_rails_workshop.md to mod2 lessons index
- Bring over Rails installation guide and task manager tutorial
- At the bottom of the lesson in the action items section, we thought it would be nice to add a tip from former alumni. We received the same advice about this specific Task Manager tutorial from alumni when we were going through this part of the program and found it really helpful so we thought it'd nice to continue to pass that along to students.
> 92 task manager   worktime  self teach

- module1/lessons/debugging_techniques.md
- module1/lessons/index.md
*This PR closes [#25](https://github.com/turingschool/curriculum-site/issues/25)*
- I am not sure if it is necessary to create a JavaScript exercise with tests specifically for this lesson? So far, I haven't added many examples for JavaScript—just a few error examples and their meanings, but no JavaScript code. Looking forward to any suggestions.
> 25 debugging techniques

- module2/lessons/index.md
- module2/lessons/sql_and_active_record.md
> Add SQL & AR lesson to index, update warmup questions

- module1/assets/event_attendees.csv
- module1/assets/full_event_attendees.csv
- module1/lessons/index.md
- module1/projects/event_manager.md
- module1/projects/index.md
None - its a supplemental used sometimes in the Mod 1 File IO lesson.  
This PR just bring the lesson plan and assets over into the SE curriculum site. 
None - merging immediately
> Event manager lesson

- module2/lessons/class_vs_instance_methods.md
- module2/lessons/index.md
- module2/lessons/intro_to_class_methods.md
This PR closes #100 
- Does this homework lesson seem too short or too detailed?
- Is it okay for the homework lesson to use the new 'intro to rails' repo from the intermission work?
> 100 class v instance methods

- module2/intermission_work/dog_party.md
This PR closes [#127](https://github.com/turingschool/curriculum-site/issues/127)
Phase Three has been added to the Dog Party lesson. This phase introduces JavaScript for handling form submission and updating the DOM. The steps include:
1.	Creating and linking a main.js file.
2.	Adding JavaScript to select DOM elements, handle form submission, and update the text of the hero section.
3.	Providing detailed explanations and code comments to ensure clarity and ease of understanding for students.
>  Add phase 3, JS

- module1/projects/connect_four/iteration_4.md
- module1/projects/futbol_pd/iterations/group_norms.md
- module1/projects/futbol_pd/iterations/retro.md
- module1/projects/http_tutorial.md
#157 
- Fixes all links in Futbol PD Project to point to the SE curriculum repo
- Adds http tutorial which is linked from the Connect Four project Iteration 4
> 157 update futbol project links

- module2/projects/hang-in-there-api/evaluation.md
- module2/projects/hang-in-there-api/index.md
- module2/projects/hang-in-there-api/requirements.md
*This PR closes #150 *
Paired project - API only where students will CRUD out a backend for the Hang in There FE.
Anything of note?
> [DRAFT] Hang In There API Project (Mod 2 Paired Project)

- module2/projects/hang-in-there-api/requirements.md
> rearrange project requirements for clarity

- module2/lessons/building_an_api.md
> Remove duplicate title

- module3/lessons/index.md
> Add lessons to lesson page m3

- module2/lessons/how_the_web_works_http.md
- module2/lessons/index.md
#130 
No major updates. 
Besides moving the exit ticket to the SE2 folder and adding an intro paragraph, the mojority of the lesson is exactly the same. Not much feedback necessary/required. Suggestions welcome, however.
> se2: how the web works 1 complete

- module2/projects/hang-in-there-api/hang_in_there_api.postman_collection.json
- module2/projects/hang-in-there-api/index.md
*This PR closes #189 *
Adds Postman collection to Mod 2 paired project
NA
> Add Postman collection to Hang in There API project

- module1/requirements/portfolio_guidelines.md
> Fix portfolio guidelines to be for all mods

- module1/lessons/slack_101.md
- module2/projects/index.md
Fix image paths in Slack 101 lesson
Expose Mod 2 project links
> fix images

- module2/lessons/index.md
- module2/lessons/model_testing.md
- Not quite, still working on calendar for #162 
I pulled over the model lesson plan and added one section -- ##What to test
Could you read it over and check for typos/readability? I only added the `## What to test?` section but everything else is the same!
> Adds model testing lesson plan to new curriculum site

- module2/lessons/one_to_many_relationships_part2.md
#228 
removing references to validations in this lesson!
> 228 remove validations

- module2/lessons/index.md
Reorganizes sections and headers on the SE2 lesson page
> Reorg lesson page for se2

- module2/lessons/js_fundamentals.md
- module2/lessons/js_intro_to_dom.md
Makes updates as I teach SE2 lessons.
Typo fix
Clarifying instructions
Updating learning goals
> Se2 on the fly

- module2/lessons/js_array_prototype_methods.md
Fixes formatting of dropdowns and adds a few more key points
> Array lesson

- module3/intermission_work/index.md
- module3/lessons/consuming_an_api_ruby.md
- module3/lessons/index.md
- module3/lessons/intro_to_soa.md
Yes #67 
- Added intermission index page for Mod 3
- Created a new submission form
- Brought over some PD curriculum items into SE mod3 drive so that links are in new drive and don't reference BE
- Built new consuming an API in Ruby lesson with Set list api
- Updated intro to SOA lesson to be done as self-teach
- did NOT do the IdeaBox (separate card for that!)
- I'd love a closer review of the Consuming an API lesson as that's what I did from scratch. All others should be minor changes/clicking through for readability and link functionality
> 67 update mod 3 intermission work

- module2/intermission_work/dog_party.md
No. Making updates after some feedback from the 2407 students.
Might be worth viewing the changes locally on localhost 🤷 
Changes include:
- Formatting updates
- CSS updates to match colors in comp
- Clarifying footer section work for students
- Adding `console.log` example dropdown
I think these updates are good to go, but any and all suggestions welcome. The one question I have is about the use of `var` in the JavaScript section. Without knowledge of what the FE teaches, I am not sure if we're still teaching it or just `let` and `const` exclusively.
> updates to the dog party intermission project

- module2/projects/hang_in_there/evaluation_rubric.md
- module2/projects/hang_in_there/index.md
This PR updates the Hang In There FE (first Se2 project) spec based on running it this first inning.
Not tied to project board.
Changes include:
- Adding bullets to JS rubric section
- Adding instructions so students know what to expect on the live evals
- swapping iteration 5 and 6 so that delete functionality is completed before the css styling
- Hides instructions to submit a PR
> Fe hang in there updates

- module0/lessons/conditionals.md
- module0/lessons/data_types.md
- module0/lessons/methods.md
- module0/lessons/problem-solving.md
- module0/prework/computer-setup.md
- module0/syllabus/index.md
This PR finishes #246 
- Combines the 3 repls needed throughout Mod 0 into one repl to use throughout.  Updates lessons to this link and adds notes about needing to delete old repls to add another once limit of 3 is reached.
- I'm reaching out to the Mod 0 team on slack about the methods lesson.  It seems like a repl might be used throughout the lesson before its actually written into the lesson to open a repl.  I've linked the new mod 0 lessons repl in that spot but am wondering if it needs to be mentioned sooner.
> Mod0 repls

- module2/lessons/networking.md
- module3/lessons/testing_tools_for_api_consumption.md
This PR includes random changes that needed made while setting up the Mod 3 calendar.
Not yet ready for review
> Calendaring se3

- module3/lessons/index.md
- module3/lessons/refactoring_api_consumption.md
Yes, closes #201 
Add a lesson plan for this class and update lesson index
- changing the language a little bit to use gateways so that students can more easily find discussion of the gateway pattern online, and so that they don't confuse their classes with Rails service objects
- doesn't include facades but links as a possible option
- includes some other design pattern links for further exploration
- Does this lesson plan adequately communicate that they are welcome to refactor in many different ways?
- Does using gateway seem reasonable? Any objections to changing up language?
- We were hoping this class would be lighter than it has been... thoughts on whether this could be true?
> M3: Refactoring API Consumption Lesson

- module2/projects/coupon-codes/front_end_requirements.md
- module2/projects/coupon-codes/index.md
adds more notes to fe requirements of coupon codes final for m2
> Add notes to coupon codes FE

- module1/lessons/js-party.md
- module2/lessons/js_approaching_problems_many_ways.md
- module2/lessons/js_array_prototype_methods.md
- module2/lessons/js_fundamentals.md
Rename se-mod2-exercises repo to Mod2-Sandbox because it was ruining my life not knowing what to call it. So I made the executive decision and executed it.
> Rename Mod 2 repo

- module3/pd/lessons/behavioral_interview_preparation.md
*This PR closes...*
*Provide a brief summary of the change(s) included in this pull request*
> add interpreting interview questions to new curric

- module3/lessons/api_authorization.md
- module3/lessons/authentication_and_authorization.md
- module3/lessons/index.md
This PR closes #199
Add a pre-work lesson and main lesson for Authentication in a Rails API
> Authorization Lesson

- module1/lessons/hashes.md
- module2/lessons/js_array_prototype_methods.md
This PR closes #255 
Remove all Jamboards before they are deprecated.
> Remove all jamboards

- module0/index.md
- module0/lessons/index.md
- module0/lessons/methods.md
- module0/prework/index.md
*These changes update the Mod 0 pages to fit the needs of intermission/expedited mod 0*
> Intermission mod0 updates

- module0/lessons/conditionals.md
- module0/lessons/methods.md
*Provide a brief summary of the change(s) included in this pull request*
Comment out conditionals and methods CFU as they are now in the session 3 assignments.
> Update mod0 site for intermission mod 0

- module2/lessons/dot_and_bracket_notation_1.md
- module2/lessons/object_literals_accessing_creating_and_modifying_values.md
❗️**This PR does not need to be merged immediately and can be placed on the back burner to focus on more pressing things.**
#188 
This PR aims to convert 2 lessons from [FE1](https://frontend.turing.edu/lessons/module-1/js-dot-bracket-notation.html) and [FE2](https://frontend.turing.edu/lessons/module-2/object-literals-accessing-creating-and-modifying-values.html). This is the conversion of FE2's lesson.
Not many updates in this one. I decided to omit any Ruby references, so this is 98% the same lesson as before. In my opinion, this lesson doesn't include anything [I don't think] that the first lesson didn't. For this, I think this second lesson could probably be sunset safely.
Changes include:
* Converting the lesson from live to async (removing language surrounding live work)
* With the …
> Dot and bracket notation 2

- module2/lessons/html_fundamentals.md
- module2/lessons/js_fundamentals.md
Updates JS Fundamentals lesson and HTML lesson
- Removes statements section from JS Fundamentals
- Adds common semantic tags to HTML lesson
> 2410 edits

- module2/lessons/js_intro_to_dom_manipulation.md
On the fly edits while teaching Intro to DOM
> 2410 day 2

- module2/lessons/js_dom_manipulation_ii.md
Adds solution to DOM II lesson
> Add solution for exercise

- module2/lessons/css_fundamentals.md
- module2/lessons/js_intro_to_dom_manipulation.md
Add CSS Zen Garden 
Remove duplicate id
> Remove duplicate id

- module4/projects/capstone/index.md
- module4/projects/index.md
- module4/projects/personal_portfolio/index.md
- module4/projects/solo_stretch_tech/index.md
No - just starting an outline for the projects page
Lists four Mod 4 projects on Projects index page and creates directory and blank index for each project
> Add Projects page outline and directories for all mod 4 projects

- module4/interview_resources/index.md
- module4/interview_resources/interview_preparation_tips.md
- module4/interview_resources/interviewing_guidelines.md
- module4/lessons/index.md
- module4/lessons/rebase_workflow.md
*This PR closes 323*
Copy over interview prep tips, interview guidelines, and rebase workflow from homework events
**Branched from Case Study project so lets review that first**
> Copy over lessons from homework events

- module4/projects/personal_portfolio/index.md
closes #305 305
Moves personal portfolio info out of calendar event and into curriculum site
> Add personal portfolio project

- module4/lessons/art_of_the_graceful_exit.md
- module4/lessons/index.md
This PR closes #314 
* [This lesson](https://mod4.turing.edu/lessons/art_of_the_graceful_exit.html) has been copied into the curriculum site.
* The only update is to combine the example questions instead of breaking them out by program
> Art of the Graceful Exit Lesson

- module4/projects/employer_case_study/evaluation.md
- module4/projects/employer_case_study/expectations.md
> fix some case study typos

- module4/interview_resources/cs_for_interviews.md
- module4/lessons/analyzing_tech_challenges.md
- module4/lessons/index.md
Closes #307 
Created a lesson plan based on a couple slide decks and worksheets in the google drive; Added very little content - I mostly copy/pasted and organized this in a lesson plan-y fashion.
This also brings in a linked lesson from the old Mod 4 site (CS for Interviews). I briefly checked for other linked resources and changed nothing. Just a direct copy/paste.
Are there areas that should be filled in with more detail?
> Create Analyzing Tech Challenges lesson

- module3/lessons/react-router.md
This PR closes issue #345 
- Comments out prework section of the lesson (left it in as a comment in case we decide to bring it back)
- Reformats the dropdowns of the lesson for more consistent flow
> Remove Router Prework

- module4/lessons/big_o.md
- module4/lessons/index.md
- module4/lessons/recursion.md
This PR closes issue #309 
This PR closes issue #308 
- Pulls recursions and big o lessons into the curriculum site
- Exposes both lessons on curriculum site
- Moves rb and js recursion exercises from abdul's github to turingschool examples git hub.  Links both in lesson so they dont need to be in the calendar event.
> Recursion and Big O

- module2/lessons/midmods_practice.md
Added note to M2 midmod practice to show them how to unfollow the instructor
> Add bullet to unfollow

- module4/intermission_work/index.md
NA
Adds Async PD Lessons to Mod 4 Intermission work
> Add async pd lessons to intermission work

- module4/final_presentation.md
- module4/index.md
closes #327
Added the Mod 4 overview and listed Graduation and Early Grad requirements
Do we need to add a Final Presentation requirement? I couldn't remember if we decided the Solo Project eval would BE the final presentation or if we expect those to be two separate things. @kaylagordon I know you've got the solo project assigned. Do you have a sense either way?
How do we feel about "Refining Your Craft" as the Mod 4 subtitle (previously was "Finding Your Specialty" which was discussed as not quite accurate in a past meeting)?
General call for feedback
> add mod 4 overview and grad requirements

- module4/projects/personal_portfolio/index.md
NA
Updates form submission link for personal portfolios
> update form link for personal portfolio submission

- module4/lessons/index.md
- module4/lessons/intro_to_background_workers.md
This PR closes #316 
This is largely a copy/paste from the Mod3 lesson.  No content updates.
> Background Workers Lesson

- module4/lessons/grouping_aggregating.md
- module4/lessons/index.md
#313 
Adds this mod 2 lesson adapted for Mod 4. Updates set list API to include a m2m complete branch that this class can start off of.
- quick read through to make sure it reads well and formatting looks ok
- sanity check on the answers to the practice problems below
> M4 Grouping and Aggregating lesson

- module4/projects/index.md
- module4/projects/tech_challenges/index.md
- module4/projects/tech_challenges/problem_solving_template.md
- module4/projects/tech_challenges/prompts.md
This PR closes issue #310 
- Pulled Tech Challenges index page, prompts page and problem solving template page into new curriculum repo.
- Reformated dropdowns
- Checked all links
- Removed broken image
- Commented out instructions to complete technical confidence check survey twice a week.
- I have assigned a different prompt to each session on the calendar (mons & fris).   There are 3 more prompts available that were not assigned (Merge Linked Lists - Subsets - What Did I Order). 
- We will want to check the links I put in the calendar after this is merged to make sure they all work.  I copy/pasted so if we just check week 2, the rest should be good. 
- Does there need to be any rhyme or reason to which prompts end up on which days/weeks?
> Tech challenges

- module4/projects/capstone/evaluation.md
- module4/projects/capstone/expectations.md
- module4/projects/capstone/index.md
- a few spelling fixes
- a few minor wording changes for clarity
- removed/shortened some wording to keep it brief without losing the content/clarity
- add SRP to rubric
- added note that both dev and review are responsible for the code pushed to production
If you don't like these changes we can scrap them and I'll just push up typo fixes :)
> Capstone edit

- module0/lessons/index.md
- module0/prework/index.md
Update Mod 0 prework index.md to include intro video
> Update Mod 0 prework index.md to include intro video

- module4/lessons/index.md
- module4/lessons/sql_ar_workshop.md
This PR closes #312 
Pulls over lesson from M2, pretty unchanged. Updates set-list API to include workshop and workshop solutions branch
> Sql ar workshop

- module2/projects/js_funk.md
This updates the jsFUNk lesson page to align with changes I made to the jsFUNk repo
> Edit jsFUNk lesson page

- module4/lessons/gathering_stories.md
- module4/lessons/index.md
This PR adds the missing PD: Interview Questions - Gathering Stories lesson for Mod 4.   
- Adds lesson to curriculum site
- Fixes links to point to curriculum site links
- Exposes lesson
> Add gathering stories pd lesson

- module4/lessons/gathering_stories.md
Remove link to career dev page full of links
> Remove link to careeddev site

- module2/projects/hang_in_there/index.md
*This PR closes...*
*Provide a brief summary of the change(s) included in this pull request*
> Unmotivational

- module4/lessons/index.md
- module4/pd/lessons/support_engineering.md
- module4/pd/lessons/tech_adjacent_roles.md
*This PR closes https://github.com/turingschool/curriculum-site/issues/320*
*Added a new page for Tech Adjacent Roles. This will be a four-part lesson where students learn about other roles that are available to them during the job hunt. This PR is specifically the overview/ introduction to the lesson and the Support Engineering lesson. *
*Video still need to be uploaded to Youtube then will be added*
> Technical Adjacent Roles -  Support Engineering lesson

- module4/pd/lessons/tech_adjacent_roles.md
- module4/pd/lessons/technical_writing_and_QA.md
*Part 2 of closing #320 *
*Lesson 2*
*Is it good?*
> TAR aka Tech Adjacent Roles Lesson 2

- module3/projects/index.md
- module4/projects/solo_stretch_tech/index.md
This PR closes #322 
New stretch tech project for M4 students to kick off on Monday of week 5.
You will want to look at the project spec AND this [deliverables google sheet](https://docs.google.com/spreadsheets/d/1dkhqQctc_6nylYyQII22zLU0He_P1k_xfaJOFngV7dM/edit?gid=0#gid=0). 
- All my questions are listed as comments.
> M4 stretch tech

- module4/pd/lessons/operations_and_reliability.md
- module4/pd/lessons/tech_adjacent_roles.md
New Tech Adjacent Roles aka TAR lesson
Operations and Reliability lesson page
> Tar lesson3

- module4/pd/lessons/education_and_community.md
- module4/pd/lessons/tech_adjacent_roles.md
TAR LESSON 4 🫡
Added final tech adjacent roles lesson. This includes a link to the page and lesson page.
> Tar lesson4

- module4/intermission_work/index.md
Update mod 4 intermission work to include Demo Showcase requirements
> Update mod 4 intermission work

- module2/lessons/js_array_prototype_methods.md
add syntax examples, remove sort from assessment list
> Array prototypes

- module4/lessons/intro-to-typescript.md
- module4/lessons/typescript-workshop.md
Changes TypeScript Workshop instructions to use Vite, not create react app
> Add Vite to link label
